services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      TZ: "UTC"
    volumes:
      - ./ahorcado:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
    command:
      - /bin/bash
      - -lc
      - |
        mkdir -p /var/www/html/storage &&
        chmod -R 777 /var/www/html/storage &&
        exec apache2-foreground
